/**
 * MarketPulse phase registry.
 * Historical phases 1-20 are documented from the current repository's README/code.
 * Phases 21-200 are controlled engineering roadmaps; a phase becomes COMPLETE
 * only after its implementation and validation gates pass.
 */
const phases = [
  {phase:1,status:"COMPLETE",title:"Core MarketPulse Foundation",description:"Initial market analytics application, supported assets/timeframes, dashboard shell and educational decision-support foundation."},
  {phase:2,status:"COMPLETE",title:"Market Analysis Layer",description:"Expanded price-action and indicator analysis, regime detection, setup classification and core market-engine plumbing."},
  {phase:3,status:"COMPLETE",title:"Trade Levels & Risk Context",description:"Entry zones, invalidation, targets and conservative trade-level geometry were added to the analysis stack."},
  {phase:4,status:"COMPLETE",title:"Learning & Signal Memory",description:"Signal/trade observations and learning hooks were introduced so resolved decisions could inform bounded historical calibration."},
  {phase:5,status:"COMPLETE",title:"Market Data & Derivatives Context",description:"Additional derivatives, order-flow and market-data context was wired into the analysis pipeline."},
  {phase:6,status:"COMPLETE",title:"Persistence & Research Foundations",description:"Durable memory, journal/state persistence and research-oriented data plumbing were established."},
  {phase:7,status:"COMPLETE",title:"Trader Analytics",description:"Journal analytics added win rate, expectancy, profit factor, average win/loss, net R, drawdown, streaks and multi-dimensional breakdowns."},
  {phase:8,status:"COMPLETE",title:"Accounts & Security",description:"Optional user accounts, secure password hashing, HTTP-only sessions, account-backed memory, rate limiting and hardened response security were added."},
  {phase:9,status:"COMPLETE",title:"Deterministic Decision Engine",description:"A single final Decision Engine combined market, multi-timeframe, derivatives/order-flow, data-quality, validation and prop-firm safety context."},
  {phase:10,status:"COMPLETE",title:"Decision Center Integration",description:"The final decision layer became the authoritative dashboard state with short caching and last-known-good fail-safe behavior."},
  {phase:11,status:"COMPLETE",title:"Live Validation Gates",description:"Current freshness, risk state, fail-safe state and historical evidence checks were placed before any live-reliance indication."},
  {phase:12,status:"COMPLETE",title:"Walk-Forward Validation",description:"Rolling historical replay of deterministic decision logic was added without future-candle lookahead and with conservative same-bar conflict handling."},
  {phase:13,status:"COMPLETE",title:"Adaptive Safety",description:"Observed out-of-sample performance can tighten confluence requirements; insufficient evidence keeps decisions PAPER_ONLY."},
  {phase:14,status:"COMPLETE",title:"Signal Intelligence",description:"Setup-specific knowledge profiles, conflict resolution, regime-aware calibration and bounded historical evidence were added for SFP, NPOC, D-Line and related setups."},
  {phase:15,status:"COMPLETE",title:"Operational Intelligence",description:"The system was extended with stronger operational/learning integrations and persistent runtime diagnostics around the decision stack."},
  {phase:16,status:"COMPLETE",title:"Watchdog & Self-Healing",description:"Continuous health checks, self-tests, load-aware behavior, incident recording and guarded remediation were introduced."},
  {phase:17,status:"COMPLETE",title:"Autotrader Safety Router",description:"Execution planning and interval/strategy routing were separated from signal logic while keeping execution behind explicit safety controls."},
  {phase:18,status:"COMPLETE",title:"Market State & Execution Routing",description:"Cross-venue market-state snapshots and a planning-only smart execution router were added, with no automatic live execution enablement."},
  {phase:19,status:"COMPLETE",title:"State Synchronization & Stability",description:"Authoritative decision/state synchronization, live-price consistency and stabilized directional presentation were strengthened across Decision Center surfaces."},
  {phase:20,status:"COMPLETE",title:"Scenario Matrix & Decision Forensics",description:"LONG, SHORT and WAIT scenarios are evaluated from one canonical snapshot with evidence, next confirmations, invalidation logic and snapshot integrity."},

  {phase:21,status:"VALIDATED",title:"Canonical State Contract",description:"Create one versioned server-side contract for price, structure, derivatives, liquidity, CVD, OI, risk, validation and decision state so every surface consumes the same normalized object."},
  {phase:22,status:"VALIDATED",title:"Authoritative State Bus",description:"Introduce a single state publication pipeline with monotonic sequence numbers, timestamps, source lineage and stale-snapshot protection across charts, Decision Center and workers."},
  {phase:23,status:"VALIDATED",title:"Directional Hysteresis Engine",description:"Make LONG/SHORT/WAIT transitions deterministic with minimum hold, confirmation count, invalidation triggers and anti-flip protection enforced server-side."},
  {phase:24,status:"VALIDATED",title:"Data Quality & Provenance Layer",description:"Score every input for freshness, completeness, venue agreement, timestamp integrity and source provenance; block downstream decisions when required evidence is unreliable."},
  {phase:25,status:"VALIDATED",title:"Cross-Exchange Flow Normalization",description:"Normalize order books, trades, funding, open interest, taker flow and CVD across venues with unit-aware transformations and missing-data rules."},
  {phase:26,status:"VALIDATED",title:"Market Regime Engine 2.0",description:"Upgrade regime detection to combine trend, volatility, liquidity, derivatives crowding and structural context with explicit transition confidence and regime history."},
  {phase:27,status:"VALIDATED",title:"Liquidity & Structure Intelligence",description:"Unify liquidity pools, sweeps, SFP, D-Line, FVG, breaker, NPOC, golden-pocket and market-structure evidence into one explainable structural graph."},
  {phase:28,status:"VALIDATED",title:"Confluence Scoring 2.0",description:"Replace loosely combined signals with bounded evidence weights, conflict penalties, regime-aware thresholds and transparent reason codes."},
  {phase:29,status:"VALIDATED",title:"Signal Calibration",description:"Calibrate historical signal probabilities/confidence against resolved outcomes while preventing future leakage and separating training, calibration and evaluation windows."},
  {phase:30,status:"VALIDATED",title:"Risk Engine 2.0",description:"Centralize risk sizing, liquidation distance, max loss, correlated exposure, daily drawdown and portfolio headroom so every decision uses the same risk contract."},
  {phase:31,status:"VALIDATED",title:"Backtest Engine 2.0",description:"Build reproducible event-driven backtesting with realistic order sequencing, fees, spread, stop/target precedence and full audit trails."},
  {phase:32,status:"VALIDATED",title:"Walk-Forward Evaluation 2.0",description:"Automate rolling train/calibrate/test windows with parameter freeze rules and out-of-sample reports by asset, regime, setup and timeframe."},
  {phase:33,status:"VALIDATED",title:"Monte Carlo & Robustness Lab",description:"Stress strategy outcomes with trade-order reshuffles, slippage shocks, gap assumptions and parameter perturbations to expose fragile edges."},
  {phase:34,status:"VALIDATED",title:"Paper Execution Simulator",description:"Create a realistic paper broker with fills, partial fills, rejected orders, order lifecycle, position state and simulated exchange responses."},
  {phase:35,status:"VALIDATED",title:"Latency & Slippage Model",description:"Measure and model signal-to-order latency, spread, market impact and adverse movement so paper results are not unrealistically optimistic."},
  {phase:36,status:"VALIDATED",title:"Signal Journal & Forensics 2.0",description:"Persist every decision snapshot, evidence set, gate result, price path and outcome so any signal can be reconstructed exactly after the fact."},
  {phase:37,status:"VALIDATED",title:"Adaptive Learning Guardrails",description:"Constrain online learning with versioned models, minimum sample sizes, rollback checkpoints, holdout protection and automatic disable-on-drift behavior."},
  {phase:38,status:"VALIDATED",title:"Drift Detection",description:"Detect changes in market behavior, feature distributions, setup frequency, hit rate and execution quality before allowing stale assumptions to propagate."},
  {phase:39,status:"VALIDATED",title:"Confidence Calibration & Scoring Audit",description:"Audit confidence against realized frequencies and expose calibration error, coverage and uncertainty instead of treating scores as certainty."},
  {phase:40,status:"VALIDATED",title:"Anomaly & Market Shock Detection",description:"Detect exchange divergences, abnormal volatility, liquidity vacuum, feed freezes, sudden OI/CVD dislocations and other conditions that should force WAIT."},
  {phase:41,status:"VALIDATED",title:"Fail-Safe & Kill-Switch Framework",description:"Add layered trading locks for bad data, model drift, loss limits, infrastructure faults and operator emergency controls with explicit recovery rules."},
  {phase:42,status:"VALIDATED",title:"Observability & SLOs",description:"Add structured telemetry for data latency, decision latency, signal stability, error rates, worker health, database health and service-level objectives."},
  {phase:43,status:"VALIDATED",title:"Admin Phase History",description:"Add a permanent owner-only evolution ledger showing Phase 1 through the current phase, what changed, validation status, commit/deploy reference and known limitations."},
  {phase:44,status:"VALIDATED",title:"Decision Explainability 2.0",description:"Make every final decision explainable from the canonical snapshot with evidence, conflicts, missing confirmations, invalidation and gate outcomes."},
  {phase:45,status:"VALIDATED",title:"Security & Secrets Review",description:"Perform a full application-security pass covering authentication, MFA, authorization boundaries, CSRF, headers, secret handling, dependency risk and admin-surface isolation."},
  {phase:46,status:"VALIDATED",title:"Deployment Safety & Canary",description:"Introduce staged deployment, health-gated rollout, rollback checkpoints and production verification so a bad release does not silently alter live decision behavior."},
  {phase:47,status:"VALIDATED",title:"Backup & Disaster Recovery",description:"Strengthen database backup verification, configuration recovery, migration safety, restore drills and lossless audit preservation."},
  {phase:48,status:"VALIDATED",title:"Performance & Scale",description:"Profile hot paths, reduce redundant market calls, optimize caches and database access, bound worker concurrency and test sustained multi-symbol load."},
  {phase:49,status:"VALIDATED_PENDING_RUNTIME",title:"Live-Readiness Gate",description:"Combine data integrity, validation, robustness, paper execution, risk, security, observability and operational evidence into one hard readiness gate."},
  {phase:50,status:"VALIDATED_PENDING_RUNTIME",title:"Controlled Live-Readiness / Shadow-to-Live",description:"Run a final shadow-mode period, verify zero critical blockers, preserve rollback controls and only then expose a separately gated live-execution capability if the evidence supports it; no profitability guarantee is implied."},
  {phase:51,status:"VALIDATED",title:"Trader Signal Contract",description:"Phase 51 trader-grade signal intelligence layer."},
  {phase:52,status:"VALIDATED",title:"Signal Qualification Gate",description:"Phase 52 trader-grade signal intelligence layer."},
  {phase:53,status:"VALIDATED",title:"Setup Ensemble 2.0",description:"Phase 53 trader-grade signal intelligence layer."},
  {phase:54,status:"VALIDATED",title:"Multi-Timeframe Alignment",description:"Phase 54 trader-grade signal intelligence layer."},
  {phase:55,status:"VALIDATED",title:"Liquidity Reaction Engine",description:"Phase 55 trader-grade signal intelligence layer."},
  {phase:56,status:"VALIDATED",title:"Structure Shift Engine",description:"Phase 56 trader-grade signal intelligence layer."},
  {phase:57,status:"VALIDATED",title:"Imbalance & FVG Context",description:"Phase 57 trader-grade signal intelligence layer."},
  {phase:58,status:"VALIDATED",title:"CVD/OI Divergence Engine",description:"Phase 58 trader-grade signal intelligence layer."},
  {phase:59,status:"VALIDATED",title:"Derivatives Crowding Engine",description:"Phase 59 trader-grade signal intelligence layer."},
  {phase:60,status:"VALIDATED",title:"Cross-Venue Consensus 2.0",description:"Phase 60 trader-grade signal intelligence layer."},
  {phase:61,status:"VALIDATED",title:"Session & Volatility Context",description:"Phase 61 trader-grade signal intelligence layer."},
  {phase:62,status:"VALIDATED",title:"Trigger Quality Engine",description:"Phase 62 trader-grade signal intelligence layer."},
  {phase:63,status:"VALIDATED",title:"Invalidation Engine 2.0",description:"Phase 63 trader-grade signal intelligence layer."},
  {phase:64,status:"VALIDATED",title:"Adaptive Levels Engine",description:"Phase 64 trader-grade signal intelligence layer."},
  {phase:65,status:"VALIDATED",title:"R:R & Expectancy Gate",description:"Phase 65 trader-grade signal intelligence layer."},
  {phase:66,status:"VALIDATED",title:"Exchange Risk Translator",description:"Phase 66 trader-grade signal intelligence layer."},
  {phase:67,status:"VALIDATED",title:"Leverage & Liquidation Safety",description:"Phase 67 trader-grade signal intelligence layer."},
  {phase:68,status:"VALIDATED",title:"Signal TTL & Aging",description:"Phase 68 trader-grade signal intelligence layer."},
  {phase:69,status:"VALIDATED",title:"Signal Lifecycle State Machine",description:"Phase 69 trader-grade signal intelligence layer."},
  {phase:70,status:"VALIDATED",title:"Anti-Chop & Cooldown",description:"Phase 70 trader-grade signal intelligence layer."},
  {phase:71,status:"VALIDATED",title:"Probability Calibration 2.0",description:"Phase 71 trader-grade signal intelligence layer."},
  {phase:72,status:"VALIDATED",title:"Ensemble Confidence Engine",description:"Phase 72 trader-grade signal intelligence layer."},
  {phase:73,status:"VALIDATED",title:"Uncertainty & Coverage Engine",description:"Phase 73 trader-grade signal intelligence layer."},
  {phase:74,status:"VALIDATED",title:"Cost-Aware Expectancy Engine",description:"Phase 74 trader-grade signal intelligence layer."},
  {phase:75,status:"VALIDATED",title:"MAE Analytics",description:"Phase 75 trader-grade signal intelligence layer."},
  {phase:76,status:"VALIDATED",title:"MFE Analytics",description:"Phase 76 trader-grade signal intelligence layer."},
  {phase:77,status:"VALIDATED",title:"False-Positive Taxonomy",description:"Phase 77 trader-grade signal intelligence layer."},
  {phase:78,status:"VALIDATED",title:"False-Negative Taxonomy",description:"Phase 78 trader-grade signal intelligence layer."},
  {phase:79,status:"VALIDATED",title:"Missed-Signal Analytics",description:"Phase 79 trader-grade signal intelligence layer."},
  {phase:80,status:"VALIDATED",title:"No-Trade Quality Engine",description:"Phase 80 trader-grade signal intelligence layer."},
  {phase:81,status:"VALIDATED",title:"Shadow Learning Engine",description:"Phase 81 trader-grade signal intelligence layer."},
  {phase:82,status:"VALIDATED",title:"Champion / Challenger Models",description:"Phase 82 trader-grade signal intelligence layer."},
  {phase:83,status:"VALIDATED",title:"Drift Recovery Engine",description:"Phase 83 trader-grade signal intelligence layer."},
  {phase:84,status:"VALIDATED",title:"Parameter Guardrails 2.0",description:"Phase 84 trader-grade signal intelligence layer."},
  {phase:85,status:"VALIDATED",title:"Live Signal Monitoring",description:"Phase 85 trader-grade signal intelligence layer."},
  {phase:86,status:"VALIDATED",title:"Symbol Correlation Engine",description:"Phase 86 trader-grade signal intelligence layer."},
  {phase:87,status:"VALIDATED",title:"Portfolio Risk Aggregator",description:"Phase 87 trader-grade signal intelligence layer."},
  {phase:88,status:"VALIDATED",title:"Event & News Risk Layer",description:"Phase 88 trader-grade signal intelligence layer."},
  {phase:89,status:"VALIDATED",title:"Exchange Health Layer",description:"Phase 89 trader-grade signal intelligence layer."},
  {phase:90,status:"VALIDATED",title:"Trader Execution Checklist",description:"Phase 90 trader-grade signal intelligence layer."},
  {phase:91,status:"VALIDATED",title:"User Context Profile",description:"Phase 91 trader-grade signal intelligence layer."},
  {phase:92,status:"VALIDATED",title:"Beginner Mode",description:"Phase 92 trader-grade signal intelligence layer."},
  {phase:93,status:"VALIDATED",title:"Decision Timeline",description:"Phase 93 trader-grade signal intelligence layer."},
  {phase:94,status:"VALIDATED",title:"Signal Notification Tiers",description:"Phase 94 trader-grade signal intelligence layer."},
  {phase:95,status:"VALIDATED",title:"Public Signal History",description:"Phase 95 trader-grade signal intelligence layer."},
  {phase:96,status:"VALIDATED",title:"Live Signal Scorecard",description:"Phase 96 trader-grade signal intelligence layer."},
  {phase:97,status:"VALIDATED",title:"Outcome Feedback Loop",description:"Phase 97 trader-grade signal intelligence layer."},
  {phase:98,status:"VALIDATED",title:"Public Audit & Transparency",description:"Phase 98 trader-grade signal intelligence layer."},
  {phase:99,status:"VALIDATED",title:"Free Public Readiness Gate",description:"Phase 99 trader-grade signal intelligence layer."},
  {phase:100,status:"VALIDATED",title:"Public Signal Gate 1.0",description:"Phase 100 trader-grade signal intelligence layer."},
  {phase:101,status:"VALIDATED",title:"Market State Reconstruction 2.0",description:"Reconstruct synchronized market state from price, candles, derivatives, liquidity and live flow."},
  {phase:102,status:"VALIDATED",title:"Microstructure Engine 2.0",description:"Measure aggressive flow, order-book pressure and execution pressure."},
  {phase:103,status:"VALIDATED",title:"Liquidity Migration Engine",description:"Track movement of nearby liquidity and price interaction with it."},
  {phase:104,status:"VALIDATED",title:"Liquidity Sweep Classification",description:"Classify sweeps as reaction, continuation, failed break or unresolved noise."},
  {phase:105,status:"VALIDATED",title:"Order-Flow Regime Detection",description:"Classify accumulation, distribution, absorption, expansion and exhaustion."},
  {phase:106,status:"VALIDATED",title:"Volume-Price Relationship Engine",description:"Detect volume and price agreement, divergence and abnormal participation."},
  {phase:107,status:"VALIDATED",title:"OI Lifecycle Engine",description:"Classify open-interest changes with price and aggressive flow."},
  {phase:108,status:"VALIDATED",title:"Funding/Basis Intelligence",description:"Turn funding and basis into contextual crowding evidence."},
  {phase:109,status:"VALIDATED",title:"Liquidation Pressure Map",description:"Map observed liquidation pressure and sensitive regions."},
  {phase:110,status:"VALIDATED",title:"Market Pressure Composite",description:"Combine pressure components while preserving provenance and uncertainty."},
  {phase:111,status:"VALIDATED",title:"Structure Engine 3.0",description:"Reconstruct higher-high/lower-low structure, BOS, CHoCH and structural state."},
  {phase:112,status:"VALIDATED",title:"Swing Quality Engine",description:"Separate meaningful swings from low-information pivots."},
  {phase:113,status:"VALIDATED",title:"SFP Intelligence 2.0",description:"Contextualize swing-failure patterns with structure and liquidity."},
  {phase:114,status:"VALIDATED",title:"D-Line Intelligence 2.0",description:"Contextualize D-Line setups with higher-timeframe structure and flow."},
  {phase:115,status:"VALIDATED",title:"FVG Quality Engine",description:"Rank imbalance zones by freshness, reaction and structure."},
  {phase:116,status:"VALIDATED",title:"Breaker / Mitigation Engine",description:"Assess breaker and mitigation zones using structural evidence."},
  {phase:117,status:"VALIDATED",title:"Golden Pocket Context Engine",description:"Use Fibonacci context only with independent structural confirmation."},
  {phase:118,status:"VALIDATED",title:"NPOC / Volume Profile Intelligence",description:"Model acceptance and rejection around volume-profile references."},
  {phase:119,status:"VALIDATED",title:"Multi-Pattern Relationship Graph",description:"Model relationships among SFP, D-Line, FVG, breaker, NPOC and liquidity."},
  {phase:120,status:"VALIDATED",title:"Price Action Narrative Engine",description:"Create a machine-readable current price-action narrative."},
  {phase:121,status:"VALIDATED",title:"12-Timeframe State Engine",description:"Build synchronized state across available timeframes."},
  {phase:122,status:"VALIDATED",title:"Timeframe Conflict Resolver",description:"Measure and classify higher/lower timeframe disagreement."},
  {phase:123,status:"VALIDATED",title:"Regime Transition Detector 3.0",description:"Detect transitions between trend, range, compression and expansion."},
  {phase:124,status:"VALIDATED",title:"Trend Strength Engine",description:"Separate persistent direction from weak directional noise."},
  {phase:125,status:"VALIDATED",title:"Range Intelligence Engine",description:"Identify range boundaries, acceptance and mean-reversion context."},
  {phase:126,status:"VALIDATED",title:"Expansion/Compression Detector",description:"Detect compression and transition into expansion."},
  {phase:127,status:"VALIDATED",title:"Breakout Quality Engine",description:"Distinguish confirmed expansion from low-quality breakout attempts."},
  {phase:128,status:"VALIDATED",title:"Reversal Probability Context",description:"Describe reversal evidence without unsupported probabilities."},
  {phase:129,status:"VALIDATED",title:"Session Transition Intelligence",description:"Track behavior around major session transitions."},
  {phase:130,status:"VALIDATED",title:"Regime-Specific Signal Policies",description:"Apply regime-specific evidence requirements."},
  {phase:131,status:"VALIDATED",title:"Signal Ensemble 2.0",description:"Combine independent evidence streams while limiting double-counting."},
  {phase:132,status:"VALIDATED",title:"Evidence Independence Engine",description:"Estimate whether confirmations represent independent evidence."},
  {phase:133,status:"VALIDATED",title:"Signal Conflict Matrix",description:"Surface contradictory evidence explicitly."},
  {phase:134,status:"VALIDATED",title:"Signal Strength Decomposition",description:"Show which evidence components contribute to direction."},
  {phase:135,status:"VALIDATED",title:"Signal Sequence Intelligence",description:"Track whether confirmation order changes signal quality."},
  {phase:136,status:"VALIDATED",title:"Setup Maturity Engine",description:"Classify setups as developing, confirmed, extended or exhausted."},
  {phase:137,status:"VALIDATED",title:"Pre-Trigger Intelligence",description:"Detect setup formation without calling it actionable."},
  {phase:138,status:"VALIDATED",title:"Trigger Confirmation 2.0",description:"Strengthen trigger confirmation using close, retest and flow conditions."},
  {phase:139,status:"VALIDATED",title:"Signal Quality Ranking Engine",description:"Produce internal evidence-quality classification without fake performance scores."},
  {phase:140,status:"VALIDATED",title:"Decision Center 3.0",description:"Create one authoritative explanation of LONG, SHORT or WAIT."},
  {phase:141,status:"VALIDATED",title:"Probability Engine 3.0",description:"Use only supplied validated probabilities."},
  {phase:142,status:"VALIDATED",title:"Regime-Conditional Probability",description:"Condition empirical probability on comparable regimes."},
  {phase:143,status:"VALIDATED",title:"Setup-Specific Probability Models",description:"Keep probability evidence segmented by setup family."},
  {phase:144,status:"VALIDATED",title:"Time-Horizon Probability Curves",description:"Represent validated outcome rates across multiple horizons."},
  {phase:145,status:"VALIDATED",title:"Calibration Engine 3.0",description:"Measure whether reported probabilities match observed frequencies."},
  {phase:146,status:"VALIDATED",title:"Reliability Curves & Calibration Error",description:"Calculate reliability and calibration error from outcome pairs."},
  {phase:147,status:"VALIDATED",title:"Uncertainty Decomposition",description:"Separate data, model and market uncertainty."},
  {phase:148,status:"VALIDATED",title:"Prediction Interval Engine",description:"Prefer ranges when point estimates imply false precision."},
  {phase:149,status:"VALIDATED",title:"Confidence Collapse Detector",description:"Detect unstable evidence that should reduce confidence."},
  {phase:150,status:"VALIDATED",title:"Prediction Evidence Ledger",description:"Create auditable evidence snapshots for predictions."},
  {phase:151,status:"VALIDATED",title:"Market Replay Engine 2.0",description:"Replay historical states using only information available at each timestamp."},
  {phase:152,status:"VALIDATED",title:"Scenario Library",description:"Build reusable historical scenario descriptors."},
  {phase:153,status:"VALIDATED",title:"Similarity Retrieval Engine",description:"Find structurally similar historical states."},
  {phase:154,status:"VALIDATED",title:"Counterfactual Analysis",description:"Compare alternative decisions without rewriting recorded history."},
  {phase:155,status:"VALIDATED",title:"Missed-Trade Analysis 2.0",description:"Separate missed opportunities from correct WAIT decisions."},
  {phase:156,status:"VALIDATED",title:"False-Positive Root Cause Engine",description:"Classify why bad signals passed."},
  {phase:157,status:"VALIDATED",title:"False-Negative Root Cause Engine",description:"Classify why useful setups were rejected."},
  {phase:158,status:"VALIDATED",title:"Feature Contribution Forensics",description:"Attribute outcomes to evidence groups without causal overclaiming."},
  {phase:159,status:"VALIDATED",title:"Learning Safety Sandbox",description:"Test learned changes in isolation."},
  {phase:160,status:"VALIDATED",title:"Evidence Promotion Engine",description:"Promote changes only after objective out-of-sample checks."},
  {phase:161,status:"VALIDATED",title:"Concept Drift Engine 2.0",description:"Detect changes in feature/outcome relationships."},
  {phase:162,status:"VALIDATED",title:"Strategy Decay Detector",description:"Detect meaningful degradation in setup behavior."},
  {phase:163,status:"VALIDATED",title:"Regime Drift Detector",description:"Detect when historical comparison populations become mismatched."},
  {phase:164,status:"VALIDATED",title:"Adaptive Threshold Engine",description:"Adjust thresholds only inside validated hard bounds."},
  {phase:165,status:"VALIDATED",title:"Champion/Challenger 2.0",description:"Compare challengers against the active baseline in shadow mode."},
  {phase:166,status:"VALIDATED",title:"Automatic Challenger Rejection",description:"Reject weak challengers without changing active logic."},
  {phase:167,status:"VALIDATED",title:"Rollback Intelligence",description:"Define deterministic rollback eligibility on degradation."},
  {phase:168,status:"VALIDATED",title:"Learning Contamination Guard",description:"Detect future leakage and timestamp contamination."},
  {phase:169,status:"VALIDATED",title:"Data Snooping Defense",description:"Track experiment reuse and overfit risk."},
  {phase:170,status:"VALIDATED",title:"Adaptive-System Audit Trail",description:"Record adaptive changes and reasons."},
  {phase:171,status:"VALIDATED",title:"Dynamic Invalidation Engine 2.0",description:"Keep invalidation structural and adaptive without weakening hard risk limits."},
  {phase:172,status:"VALIDATED",title:"Dynamic TP Architecture",description:"Build targets from structure and empirical excursion."},
  {phase:173,status:"VALIDATED",title:"MAE/MFE Distribution Engine 2.0",description:"Use empirical excursion distributions for planning."},
  {phase:174,status:"VALIDATED",title:"Slippage Scenario Engine 2.0",description:"Stress planned execution under slippage scenarios."},
  {phase:175,status:"VALIDATED",title:"Fee & Funding Impact Engine 2.0",description:"Include trading costs in expectancy context."},
  {phase:176,status:"VALIDATED",title:"Position-Sizing Evidence Engine",description:"Tie sizing context to volatility, structure and hard limits."},
  {phase:177,status:"VALIDATED",title:"Correlation Stress Engine",description:"Detect hidden concentration across positions."},
  {phase:178,status:"VALIDATED",title:"Liquidation Safety Engine",description:"Detect dangerous leverage and liquidation distances."},
  {phase:179,status:"VALIDATED",title:"Exchange Execution Context",description:"Track exchange-specific execution assumptions and constraints."},
  {phase:180,status:"VALIDATED",title:"Manual Execution Safety Router 2.0",description:"Keep execution decision-support-only and route unsafe conditions away from action."},
  {phase:181,status:"VALIDATED",title:"Decision Center 4.0",description:"Create a structured explanation-first trader cockpit payload."},
  {phase:182,status:"VALIDATED",title:"Signal Timeline",description:"Represent signal development and state transitions."},
  {phase:183,status:"VALIDATED",title:"Live Evidence Map",description:"Present synchronized liquidity, flow, structure and trigger relationships."},
  {phase:184,status:"VALIDATED",title:"Why No Trade 2.0",description:"Create precise blocker hierarchy and next-confirmation guidance."},
  {phase:185,status:"VALIDATED",title:"Trade Preparation Mode",description:"Show what must happen before a developing setup becomes actionable."},
  {phase:186,status:"VALIDATED",title:"Signal Lifecycle UI",description:"Expose setup lifecycle from developing to expired."},
  {phase:187,status:"VALIDATED",title:"Beginner/Advanced Adaptive UI",description:"Change explanation depth without changing underlying decisions."},
  {phase:188,status:"VALIDATED",title:"Mobile Trading Cockpit",description:"Return compact decision-support presentation metadata."},
  {phase:189,status:"VALIDATED",title:"Alert Intelligence 2.0",description:"Emit material-state-change notifications rather than repeats."},
  {phase:190,status:"VALIDATED",title:"Personal Trading Journal Integration",description:"Package structured decision records for journal persistence."},
  {phase:191,status:"VALIDATED",title:"Admin Intelligence Console 2.0",description:"Expose an admin intelligence summary."},
  {phase:192,status:"VALIDATED",title:"Signal Forensics Dashboard",description:"Provide signal evidence and outcome-forensics metadata."},
  {phase:193,status:"VALIDATED",title:"Model Health Dashboard",description:"Summarize calibration, drift, errors, latency and quality."},
  {phase:194,status:"VALIDATED",title:"Data Source Reliability Matrix",description:"Summarize source freshness, availability and disagreement."},
  {phase:195,status:"VALIDATED",title:"Incident Detection & Response Engine",description:"Identify feed, staleness and consistency incidents."},
  {phase:196,status:"VALIDATED",title:"System Self-Test 2.0",description:"Run deterministic integrity checks across the advanced pipeline."},
  {phase:197,status:"VALIDATED",title:"Public Transparency Center",description:"Prepare public-safe outcome and methodology metadata."},
  {phase:198,status:"VALIDATED",title:"User Safety Center",description:"Expose risk, leverage, staleness and execution warnings."},
  {phase:199,status:"VALIDATED",title:"Public Signal Trust Layer",description:"Require evidence-backed readiness for public signal presentation."},
  {phase:200,status:"VALIDATED",title:"MarketPulse Intelligence OS 2.0",description:"Finalize the integrated controlled promotion contract."},
  {phase:201,status:"VALIDATED",title:"Edge Baseline Lock",description:"Edge Baseline Lock."},
  {phase:202,status:"VALIDATED",title:"Empirical Probability Integrity",description:"Empirical Probability Integrity."},
  {phase:203,status:"VALIDATED",title:"Expected-R Engine",description:"Expected-R Engine."},
  {phase:204,status:"VALIDATED",title:"Cost-Aware Edge",description:"Cost-Aware Edge."},
  {phase:205,status:"VALIDATED",title:"Slippage Stress Gate",description:"Slippage Stress Gate."},
  {phase:206,status:"VALIDATED",title:"Spread Stress Gate",description:"Spread Stress Gate."},
  {phase:207,status:"VALIDATED",title:"Reward Compression Detector",description:"Reward Compression Detector."},
  {phase:208,status:"VALIDATED",title:"Win-Rate Fragility Test",description:"Win-Rate Fragility Test."},
  {phase:209,status:"VALIDATED",title:"Bayesian Edge Shrinkage",description:"Bayesian Edge Shrinkage."},
  {phase:210,status:"VALIDATED",title:"Probability Floor Gate",description:"Probability Floor Gate."},
  {phase:211,status:"VALIDATED",title:"R:R Integrity Gate",description:"R:R Integrity Gate."},
  {phase:212,status:"VALIDATED",title:"Target Ladder Quality",description:"Target Ladder Quality."},
  {phase:213,status:"VALIDATED",title:"Invalidation Distance Quality",description:"Invalidation Distance Quality."},
  {phase:214,status:"VALIDATED",title:"MAE Budget Check",description:"MAE Budget Check."},
  {phase:215,status:"VALIDATED",title:"MFE Capture Check",description:"MFE Capture Check."},
  {phase:216,status:"VALIDATED",title:"Volatility-Normalized Stop",description:"Volatility-Normalized Stop."},
  {phase:217,status:"VALIDATED",title:"Volatility-Normalized Target",description:"Volatility-Normalized Target."},
  {phase:218,status:"VALIDATED",title:"ATR Expansion Penalty",description:"ATR Expansion Penalty."},
  {phase:219,status:"VALIDATED",title:"ATR Compression Opportunity",description:"ATR Compression Opportunity."},
  {phase:220,status:"VALIDATED",title:"Trend Persistence Filter",description:"Trend Persistence Filter."},
  {phase:221,status:"VALIDATED",title:"Range Boundary Filter",description:"Range Boundary Filter."},
  {phase:222,status:"VALIDATED",title:"Breakout Acceptance Filter",description:"Breakout Acceptance Filter."},
  {phase:223,status:"VALIDATED",title:"Retest Quality Filter",description:"Retest Quality Filter."},
  {phase:224,status:"VALIDATED",title:"SFP Reclaim Integrity",description:"SFP Reclaim Integrity."},
  {phase:225,status:"VALIDATED",title:"D-Line Confluence Integrity",description:"D-Line Confluence Integrity."},
  {phase:226,status:"VALIDATED",title:"FVG Freshness Filter",description:"FVG Freshness Filter."},
  {phase:227,status:"VALIDATED",title:"Breaker Validity Filter",description:"Breaker Validity Filter."},
  {phase:228,status:"VALIDATED",title:"Golden Pocket Independence",description:"Golden Pocket Independence."},
  {phase:229,status:"VALIDATED",title:"NPOC Acceptance Filter",description:"NPOC Acceptance Filter."},
  {phase:230,status:"VALIDATED",title:"Liquidity Sweep Followthrough",description:"Liquidity Sweep Followthrough."},
  {phase:231,status:"VALIDATED",title:"Liquidity Refill Detection",description:"Liquidity Refill Detection."},
  {phase:232,status:"VALIDATED",title:"Liquidity Vacuum Detector",description:"Liquidity Vacuum Detector."},
  {phase:233,status:"VALIDATED",title:"Order-Book Imbalance Stability",description:"Order-Book Imbalance Stability."},
  {phase:234,status:"VALIDATED",title:"Taker Flow Persistence",description:"Taker Flow Persistence."},
  {phase:235,status:"VALIDATED",title:"CVD Direction Integrity",description:"CVD Direction Integrity."},
  {phase:236,status:"VALIDATED",title:"OI-Price Compatibility",description:"OI-Price Compatibility."},
  {phase:237,status:"VALIDATED",title:"Funding Crowding Penalty",description:"Funding Crowding Penalty."},
  {phase:238,status:"VALIDATED",title:"Basis Stability Filter",description:"Basis Stability Filter."},
  {phase:239,status:"VALIDATED",title:"Liquidation Followthrough",description:"Liquidation Followthrough."},
  {phase:240,status:"VALIDATED",title:"Cross-Venue Consensus Gate",description:"Cross-Venue Consensus Gate."},
  {phase:241,status:"VALIDATED",title:"Price Dispersion Gate",description:"Price Dispersion Gate."},
  {phase:242,status:"VALIDATED",title:"Feed Freshness Gate",description:"Feed Freshness Gate."},
  {phase:243,status:"VALIDATED",title:"Provider Diversity Score",description:"Provider Diversity Score."},
  {phase:244,status:"VALIDATED",title:"Derivative Availability Gate",description:"Derivative Availability Gate."},
  {phase:245,status:"VALIDATED",title:"Candle Closure Integrity",description:"Candle Closure Integrity."},
  {phase:246,status:"VALIDATED",title:"Snapshot Hash Integrity",description:"Snapshot Hash Integrity."},
  {phase:247,status:"VALIDATED",title:"MTF Alignment Score",description:"MTF Alignment Score."},
  {phase:248,status:"VALIDATED",title:"MTF Conflict Penalty",description:"MTF Conflict Penalty."},
  {phase:249,status:"VALIDATED",title:"Session Quality Filter",description:"Session Quality Filter."},
  {phase:250,status:"VALIDATED",title:"Session Transition Risk",description:"Session Transition Risk."},
  {phase:251,status:"VALIDATED",title:"Entry Timing Efficiency",description:"Entry Timing Efficiency."},
  {phase:252,status:"VALIDATED",title:"Chase Detector",description:"Chase Detector."},
  {phase:253,status:"VALIDATED",title:"Late-Trigger Detector",description:"Late-Trigger Detector."},
  {phase:254,status:"VALIDATED",title:"Cooldown Integrity",description:"Cooldown Integrity."},
  {phase:255,status:"VALIDATED",title:"Daily Drawdown Headroom",description:"Daily Drawdown Headroom."},
  {phase:256,status:"VALIDATED",title:"Portfolio Concentration Gate",description:"Portfolio Concentration Gate."},
  {phase:257,status:"VALIDATED",title:"Correlation Shock Filter",description:"Correlation Shock Filter."},
  {phase:258,status:"VALIDATED",title:"Leverage Safety Gate",description:"Leverage Safety Gate."},
  {phase:259,status:"VALIDATED",title:"Liquidation Distance Gate",description:"Liquidation Distance Gate."},
  {phase:260,status:"VALIDATED",title:"Position Size Stability",description:"Position Size Stability."},
  {phase:261,status:"VALIDATED",title:"Risk Per Trade Ceiling",description:"Risk Per Trade Ceiling."},
  {phase:262,status:"VALIDATED",title:"Risk Reward Floor",description:"Risk Reward Floor."},
  {phase:263,status:"VALIDATED",title:"Execution Venue Constraint",description:"Execution Venue Constraint."},
  {phase:264,status:"VALIDATED",title:"Execution Latency Budget",description:"Execution Latency Budget."},
  {phase:265,status:"VALIDATED",title:"Order-Type Suitability",description:"Order-Type Suitability."},
  {phase:266,status:"VALIDATED",title:"Partial Fill Risk",description:"Partial Fill Risk."},
  {phase:267,status:"VALIDATED",title:"Fee Tier Sensitivity",description:"Fee Tier Sensitivity."},
  {phase:268,status:"VALIDATED",title:"Funding Cost Sensitivity",description:"Funding Cost Sensitivity."},
  {phase:269,status:"VALIDATED",title:"Overnight Carry Penalty",description:"Overnight Carry Penalty."},
  {phase:270,status:"VALIDATED",title:"Net Expected Value",description:"Net Expected Value."},
  {phase:271,status:"VALIDATED",title:"Expectancy Confidence Band",description:"Expectancy Confidence Band."},
  {phase:272,status:"VALIDATED",title:"Minimum Edge Margin",description:"Minimum Edge Margin."},
  {phase:273,status:"VALIDATED",title:"Edge-to-Noise Ratio",description:"Edge-to-Noise Ratio."},
  {phase:274,status:"VALIDATED",title:"Setup Regime Match",description:"Setup Regime Match."},
  {phase:275,status:"VALIDATED",title:"Historical Analog Match",description:"Historical Analog Match."},
  {phase:276,status:"VALIDATED",title:"Out-of-Sample Evidence Gate",description:"Out-of-Sample Evidence Gate."},
  {phase:277,status:"VALIDATED",title:"Sample Depth Gate",description:"Sample Depth Gate."},
  {phase:278,status:"VALIDATED",title:"Drift Safety Gate",description:"Drift Safety Gate."},
  {phase:279,status:"VALIDATED",title:"Challenger Safety Gate",description:"Challenger Safety Gate."},
  {phase:280,status:"VALIDATED",title:"Leakage Guard",description:"Leakage Guard."},
  {phase:281,status:"VALIDATED",title:"Data-Snooping Guard",description:"Data-Snooping Guard."},
  {phase:282,status:"VALIDATED",title:"False-Positive Suppression",description:"False-Positive Suppression."},
  {phase:283,status:"VALIDATED",title:"False-Negative Review",description:"False-Negative Review."},
  {phase:284,status:"VALIDATED",title:"Signal Stability Gate",description:"Signal Stability Gate."},
  {phase:285,status:"VALIDATED",title:"Signal Hysteresis Gate",description:"Signal Hysteresis Gate."},
  {phase:286,status:"VALIDATED",title:"Trigger Sequence Integrity",description:"Trigger Sequence Integrity."},
  {phase:287,status:"VALIDATED",title:"Signal Maturity Gate",description:"Signal Maturity Gate."},
  {phase:288,status:"VALIDATED",title:"Conflict Resolution Gate",description:"Conflict Resolution Gate."},
  {phase:289,status:"VALIDATED",title:"Confluence Independence Gate",description:"Confluence Independence Gate."},
  {phase:290,status:"VALIDATED",title:"Probability Calibration Error Gate",description:"Probability Calibration Error Gate."},
  {phase:291,status:"VALIDATED",title:"Reliability-Bucket Gate",description:"Reliability-Bucket Gate."},
  {phase:292,status:"VALIDATED",title:"Outcome Horizon Match",description:"Outcome Horizon Match."},
  {phase:293,status:"VALIDATED",title:"Walk-Forward Stability Gate",description:"Walk-Forward Stability Gate."},
  {phase:294,status:"VALIDATED",title:"Monte-Carlo Drawdown Stress",description:"Monte-Carlo Drawdown Stress."},
  {phase:295,status:"VALIDATED",title:"Tail-Loss Stress",description:"Tail-Loss Stress."},
  {phase:296,status:"VALIDATED",title:"Profit-Factor Integrity",description:"Profit-Factor Integrity."},
  {phase:297,status:"VALIDATED",title:"Expectancy Decay Detector",description:"Expectancy Decay Detector."},
  {phase:298,status:"VALIDATED",title:"Regime-Specific Decay Detector",description:"Regime-Specific Decay Detector."},
  {phase:299,status:"VALIDATED",title:"Signal Frequency Governor",description:"Signal Frequency Governor."},
  {phase:300,status:"VALIDATED",title:"Profit Engine Final Gate",description:"Profit Engine Final Gate."}
  {phase:301,status:"VALIDATED",title:"Regime Fingerprint Engine",description:"Phase 301: Regime Fingerprint Engine — integrated adaptive intelligence capability."},
  {phase:302,status:"VALIDATED",title:"Trend Range Expansion Classifier",description:"Phase 302: Trend Range Expansion Classifier — integrated adaptive intelligence capability."},
  {phase:303,status:"VALIDATED",title:"Volatility Regime Map",description:"Phase 303: Volatility Regime Map — integrated adaptive intelligence capability."},
  {phase:304,status:"VALIDATED",title:"Liquidity Regime Map",description:"Phase 304: Liquidity Regime Map — integrated adaptive intelligence capability."},
  {phase:305,status:"VALIDATED",title:"Flow Regime Map",description:"Phase 305: Flow Regime Map — integrated adaptive intelligence capability."},
  {phase:306,status:"VALIDATED",title:"Derivatives Regime Map",description:"Phase 306: Derivatives Regime Map — integrated adaptive intelligence capability."},
  {phase:307,status:"VALIDATED",title:"Correlation Regime Map",description:"Phase 307: Correlation Regime Map — integrated adaptive intelligence capability."},
  {phase:308,status:"VALIDATED",title:"Session Regime Map",description:"Phase 308: Session Regime Map — integrated adaptive intelligence capability."},
  {phase:309,status:"VALIDATED",title:"Regime Transition Detector",description:"Phase 309: Regime Transition Detector — integrated adaptive intelligence capability."},
  {phase:310,status:"VALIDATED",title:"Regime Confidence Score",description:"Phase 310: Regime Confidence Score — integrated adaptive intelligence capability."},
  {phase:311,status:"VALIDATED",title:"Market State Fingerprinting",description:"Phase 311: Market State Fingerprinting — integrated adaptive intelligence capability."},
  {phase:312,status:"VALIDATED",title:"Historical State Retrieval",description:"Phase 312: Historical State Retrieval — integrated adaptive intelligence capability."},
  {phase:313,status:"VALIDATED",title:"Nearest Market Analog Engine",description:"Phase 313: Nearest Market Analog Engine — integrated adaptive intelligence capability."},
  {phase:314,status:"VALIDATED",title:"Analog Similarity Scoring",description:"Phase 314: Analog Similarity Scoring — integrated adaptive intelligence capability."},
  {phase:315,status:"VALIDATED",title:"Outcome Distribution Retrieval",description:"Phase 315: Outcome Distribution Retrieval — integrated adaptive intelligence capability."},
  {phase:316,status:"VALIDATED",title:"Regime Conditioned Memory",description:"Phase 316: Regime Conditioned Memory — integrated adaptive intelligence capability."},
  {phase:317,status:"VALIDATED",title:"Setup Specific Memory",description:"Phase 317: Setup Specific Memory — integrated adaptive intelligence capability."},
  {phase:318,status:"VALIDATED",title:"Timeframe Specific Memory",description:"Phase 318: Timeframe Specific Memory — integrated adaptive intelligence capability."},
  {phase:319,status:"VALIDATED",title:"Session Specific Memory",description:"Phase 319: Session Specific Memory — integrated adaptive intelligence capability."},
  {phase:320,status:"VALIDATED",title:"Historical Memory Confidence Gate",description:"Phase 320: Historical Memory Confidence Gate — integrated adaptive intelligence capability."},
  {phase:321,status:"VALIDATED",title:"Setup DNA Generator",description:"Phase 321: Setup DNA Generator — integrated adaptive intelligence capability."},
  {phase:322,status:"VALIDATED",title:"Structure DNA",description:"Phase 322: Structure DNA — integrated adaptive intelligence capability."},
  {phase:323,status:"VALIDATED",title:"Liquidity DNA",description:"Phase 323: Liquidity DNA — integrated adaptive intelligence capability."},
  {phase:324,status:"VALIDATED",title:"Flow DNA",description:"Phase 324: Flow DNA — integrated adaptive intelligence capability."},
  {phase:325,status:"VALIDATED",title:"Derivatives DNA",description:"Phase 325: Derivatives DNA — integrated adaptive intelligence capability."},
  {phase:326,status:"VALIDATED",title:"Timing DNA",description:"Phase 326: Timing DNA — integrated adaptive intelligence capability."},
  {phase:327,status:"VALIDATED",title:"Entry DNA",description:"Phase 327: Entry DNA — integrated adaptive intelligence capability."},
  {phase:328,status:"VALIDATED",title:"Invalidation DNA",description:"Phase 328: Invalidation DNA — integrated adaptive intelligence capability."},
  {phase:329,status:"VALIDATED",title:"Target DNA",description:"Phase 329: Target DNA — integrated adaptive intelligence capability."},
  {phase:330,status:"VALIDATED",title:"Full Setup Fingerprint",description:"Phase 330: Full Setup Fingerprint — integrated adaptive intelligence capability."},
  {phase:331,status:"VALIDATED",title:"Outcome Attribution Engine",description:"Phase 331: Outcome Attribution Engine — integrated adaptive intelligence capability."},
  {phase:332,status:"VALIDATED",title:"Prediction Outcome Recorder",description:"Phase 332: Prediction Outcome Recorder — integrated adaptive intelligence capability."},
  {phase:333,status:"VALIDATED",title:"Feature Contribution Tracking",description:"Phase 333: Feature Contribution Tracking — integrated adaptive intelligence capability."},
  {phase:334,status:"VALIDATED",title:"Winning Pattern Memory",description:"Phase 334: Winning Pattern Memory — integrated adaptive intelligence capability."},
  {phase:335,status:"VALIDATED",title:"Losing Pattern Memory",description:"Phase 335: Losing Pattern Memory — integrated adaptive intelligence capability."},
  {phase:336,status:"VALIDATED",title:"False Positive Learning Loop",description:"Phase 336: False Positive Learning Loop — integrated adaptive intelligence capability."},
  {phase:337,status:"VALIDATED",title:"False Negative Learning Loop",description:"Phase 337: False Negative Learning Loop — integrated adaptive intelligence capability."},
  {phase:338,status:"VALIDATED",title:"Regime Specific Learning",description:"Phase 338: Regime Specific Learning — integrated adaptive intelligence capability."},
  {phase:339,status:"VALIDATED",title:"Adaptive Weight Proposal",description:"Phase 339: Adaptive Weight Proposal — integrated adaptive intelligence capability."},
  {phase:340,status:"VALIDATED",title:"Learning Promotion Gate",description:"Phase 340: Learning Promotion Gate — integrated adaptive intelligence capability."},
  {phase:341,status:"VALIDATED",title:"Rolling Backtest Engine",description:"Phase 341: Rolling Backtest Engine — integrated adaptive intelligence capability."},
  {phase:342,status:"VALIDATED",title:"Walk Forward Laboratory",description:"Phase 342: Walk Forward Laboratory — integrated adaptive intelligence capability."},
  {phase:343,status:"VALIDATED",title:"Regime Stratified Backtest",description:"Phase 343: Regime Stratified Backtest — integrated adaptive intelligence capability."},
  {phase:344,status:"VALIDATED",title:"Session Stratified Backtest",description:"Phase 344: Session Stratified Backtest — integrated adaptive intelligence capability."},
  {phase:345,status:"VALIDATED",title:"Setup Stratified Backtest",description:"Phase 345: Setup Stratified Backtest — integrated adaptive intelligence capability."},
  {phase:346,status:"VALIDATED",title:"Long Short Symmetry Test",description:"Phase 346: Long Short Symmetry Test — integrated adaptive intelligence capability."},
  {phase:347,status:"VALIDATED",title:"Parameter Sensitivity Test",description:"Phase 347: Parameter Sensitivity Test — integrated adaptive intelligence capability."},
  {phase:348,status:"VALIDATED",title:"Probability Calibration Test",description:"Phase 348: Probability Calibration Test — integrated adaptive intelligence capability."},
  {phase:349,status:"VALIDATED",title:"Monte Carlo Confidence Engine",description:"Phase 349: Monte Carlo Confidence Engine — integrated adaptive intelligence capability."},
  {phase:350,status:"VALIDATED",title:"Model Promotion Scorecard",description:"Phase 350: Model Promotion Scorecard — integrated adaptive intelligence capability."},
  {phase:351,status:"VALIDATED",title:"Structure Analyst",description:"Phase 351: Structure Analyst — integrated adaptive intelligence capability."},
  {phase:352,status:"VALIDATED",title:"Liquidity Analyst",description:"Phase 352: Liquidity Analyst — integrated adaptive intelligence capability."},
  {phase:353,status:"VALIDATED",title:"Order Flow Analyst",description:"Phase 353: Order Flow Analyst — integrated adaptive intelligence capability."},
  {phase:354,status:"VALIDATED",title:"Derivatives Analyst",description:"Phase 354: Derivatives Analyst — integrated adaptive intelligence capability."},
  {phase:355,status:"VALIDATED",title:"Momentum Analyst",description:"Phase 355: Momentum Analyst — integrated adaptive intelligence capability."},
  {phase:356,status:"VALIDATED",title:"Regime Analyst",description:"Phase 356: Regime Analyst — integrated adaptive intelligence capability."},
  {phase:357,status:"VALIDATED",title:"Risk Analyst",description:"Phase 357: Risk Analyst — integrated adaptive intelligence capability."},
  {phase:358,status:"VALIDATED",title:"Execution Analyst",description:"Phase 358: Execution Analyst — integrated adaptive intelligence capability."},
  {phase:359,status:"VALIDATED",title:"Evidence Arbitration",description:"Phase 359: Evidence Arbitration — integrated adaptive intelligence capability."},
  {phase:360,status:"VALIDATED",title:"Master Decision Council",description:"Phase 360: Master Decision Council — integrated adaptive intelligence capability."},
  {phase:361,status:"VALIDATED",title:"Real Time Event Detector",description:"Phase 361: Real Time Event Detector — integrated adaptive intelligence capability."},
  {phase:362,status:"VALIDATED",title:"Liquidity Sweep Event",description:"Phase 362: Liquidity Sweep Event — integrated adaptive intelligence capability."},
  {phase:363,status:"VALIDATED",title:"CVD Flip Event",description:"Phase 363: CVD Flip Event — integrated adaptive intelligence capability."},
  {phase:364,status:"VALIDATED",title:"OI Shock Event",description:"Phase 364: OI Shock Event — integrated adaptive intelligence capability."},
  {phase:365,status:"VALIDATED",title:"Liquidation Event",description:"Phase 365: Liquidation Event — integrated adaptive intelligence capability."},
  {phase:366,status:"VALIDATED",title:"Volatility Explosion Event",description:"Phase 366: Volatility Explosion Event — integrated adaptive intelligence capability."},
  {phase:367,status:"VALIDATED",title:"Breakout Event",description:"Phase 367: Breakout Event — integrated adaptive intelligence capability."},
  {phase:368,status:"VALIDATED",title:"Failed Breakout Event",description:"Phase 368: Failed Breakout Event — integrated adaptive intelligence capability."},
  {phase:369,status:"VALIDATED",title:"Structure Flip Event",description:"Phase 369: Structure Flip Event — integrated adaptive intelligence capability."},
  {phase:370,status:"VALIDATED",title:"Composite Market Event Engine",description:"Phase 370: Composite Market Event Engine — integrated adaptive intelligence capability."},
  {phase:371,status:"VALIDATED",title:"Entry Zone Engine",description:"Phase 371: Entry Zone Engine — integrated adaptive intelligence capability."},
  {phase:372,status:"VALIDATED",title:"Optimal Entry Locator",description:"Phase 372: Optimal Entry Locator — integrated adaptive intelligence capability."},
  {phase:373,status:"VALIDATED",title:"Confirmation Entry Mode",description:"Phase 373: Confirmation Entry Mode — integrated adaptive intelligence capability."},
  {phase:374,status:"VALIDATED",title:"Aggressive Entry Mode",description:"Phase 374: Aggressive Entry Mode — integrated adaptive intelligence capability."},
  {phase:375,status:"VALIDATED",title:"Conservative Entry Mode",description:"Phase 375: Conservative Entry Mode — integrated adaptive intelligence capability."},
  {phase:376,status:"VALIDATED",title:"Invalidation Precision Engine",description:"Phase 376: Invalidation Precision Engine — integrated adaptive intelligence capability."},
  {phase:377,status:"VALIDATED",title:"Target Optimization Engine",description:"Phase 377: Target Optimization Engine — integrated adaptive intelligence capability."},
  {phase:378,status:"VALIDATED",title:"Dynamic RR Mapping",description:"Phase 378: Dynamic RR Mapping — integrated adaptive intelligence capability."},
  {phase:379,status:"VALIDATED",title:"Entry Quality Score",description:"Phase 379: Entry Quality Score — integrated adaptive intelligence capability."},
  {phase:380,status:"VALIDATED",title:"Execution Readiness Score",description:"Phase 380: Execution Readiness Score — integrated adaptive intelligence capability."},
  {phase:381,status:"VALIDATED",title:"Signal Failure Detector",description:"Phase 381: Signal Failure Detector — integrated adaptive intelligence capability."},
  {phase:382,status:"VALIDATED",title:"Early Invalidation Detector",description:"Phase 382: Early Invalidation Detector — integrated adaptive intelligence capability."},
  {phase:383,status:"VALIDATED",title:"Thesis Degradation Detector",description:"Phase 383: Thesis Degradation Detector — integrated adaptive intelligence capability."},
  {phase:384,status:"VALIDATED",title:"Liquidity Failure Detector",description:"Phase 384: Liquidity Failure Detector — integrated adaptive intelligence capability."},
  {phase:385,status:"VALIDATED",title:"Flow Failure Detector",description:"Phase 385: Flow Failure Detector — integrated adaptive intelligence capability."},
  {phase:386,status:"VALIDATED",title:"Structure Failure Detector",description:"Phase 386: Structure Failure Detector — integrated adaptive intelligence capability."},
  {phase:387,status:"VALIDATED",title:"Probability Collapse Detector",description:"Phase 387: Probability Collapse Detector — integrated adaptive intelligence capability."},
  {phase:388,status:"VALIDATED",title:"Target Failure Detector",description:"Phase 388: Target Failure Detector — integrated adaptive intelligence capability."},
  {phase:389,status:"VALIDATED",title:"Emergency WAIT Transition",description:"Phase 389: Emergency WAIT Transition — integrated adaptive intelligence capability."},
  {phase:390,status:"VALIDATED",title:"Post Failure Forensics",description:"Phase 390: Post Failure Forensics — integrated adaptive intelligence capability."},
  {phase:391,status:"VALIDATED",title:"Unified MarketPulse State",description:"Phase 391: Unified MarketPulse State — integrated adaptive intelligence capability."},
  {phase:392,status:"VALIDATED",title:"Decision Center 2.0",description:"Phase 392: Decision Center 2.0 — integrated adaptive intelligence capability."},
  {phase:393,status:"VALIDATED",title:"Live Signal Timeline 2.0",description:"Phase 393: Live Signal Timeline 2.0 — integrated adaptive intelligence capability."},
  {phase:394,status:"VALIDATED",title:"Why No Trade 2.0",description:"Phase 394: Why No Trade 2.0 — integrated adaptive intelligence capability."},
  {phase:395,status:"VALIDATED",title:"Evidence Explorer",description:"Phase 395: Evidence Explorer — integrated adaptive intelligence capability."},
  {phase:396,status:"VALIDATED",title:"Signal Replay Mode",description:"Phase 396: Signal Replay Mode — integrated adaptive intelligence capability."},
  {phase:397,status:"VALIDATED",title:"Market Playback Mode",description:"Phase 397: Market Playback Mode — integrated adaptive intelligence capability."},
  {phase:398,status:"VALIDATED",title:"Admin Intelligence Console 2.0",description:"Phase 398: Admin Intelligence Console 2.0 — integrated adaptive intelligence capability."},
  {phase:399,status:"VALIDATED",title:"System Integrity Monitor",description:"Phase 399: System Integrity Monitor — integrated adaptive intelligence capability."},
  {phase:400,status:"VALIDATED",title:"Autonomous Intelligence Core",description:"Phase 400: Autonomous Intelligence Core — integrated adaptive intelligence capability."},
];

function getPromotionSummary(){
  return {
    engineeringStatus:"PROMOTED",
    engineeringPhase:400,
    validatedThrough:400,
    validatedAt:"2026-09-29T09:07:46Z",
    validationBasis:["GitHub Actions Phase 201–300 Validation run #4","Phase 201–300 self-test","canonical npm regression suite","full regression suite"],
    liveReadinessStatus:"RUNTIME_GATED_LIVE_SIGNAL_PATH",
    liveReadinessPhase:400,
    liveReadinessBlockers:["PHASE_49_RUNTIME_READINESS","PHASE_50_SHADOW_TO_LIVE"],
    automaticExecutionEnabled:false,
    signalEngineVersion:"400.0.0",
    note:"Phase 201–300 adds a runtime-gated live-signal path based on validated probability, positive expected R, data quality, risk and out-of-sample controls. It does not guarantee profitability and does not enable automatic execution."
  };
}
function getEngineeringPhase(){ return 400; }
function getPhaseHistory(){
  return phases.map(p=>({...p}));
}
function getCurrentPhase(){
  const complete=phases.filter(p=>p.status==="COMPLETE");
  return complete.length?Math.max(...complete.map(p=>p.phase)):0;
}
module.exports={phases,getPhaseHistory,getCurrentPhase,getPromotionSummary,getEngineeringPhase};
