/**
 * MarketPulse phase registry.
 * Historical phases 1-20 are documented from the current repository's README/code.
 * Phases 21-200 are controlled engineering roadmaps; a phase becomes COMPLETE
 * only after its implementation and validation gates pass.
 */
const phases = [
  {phase:1,status:"COMPLETE",title:"Core MarketPulse Foundation",description:"Initial market analytics application, supported assets/timeframes, dashboard shell and educational decision-support foundation."},
  {phase:2,status:"COMPLETE",title:"Market Analysis Layer",description:"Expanded price-action and indicator analysis, regime detection, setup classification and core market-engine plumbing."},
  {phase:3,status:"COMPLETE",title:"Trade Levels & Risk Context",description:"Entry zones, invalidation, targets and conservative trade-level geometry were added to the analysis stack."},
  {phase:4,status:"COMPLETE",title:"Learning & Signal Memory",description:"Signal/trade observations and learning hooks were introduced so resolved decisions could inform bounded historical calibration."},
  {phase:5,status:"COMPLETE",title:"Market Data & Derivatives Context",description:"Additional derivatives, order-flow and market-data context was wired into the analysis pipeline."},
  {phase:6,status:"COMPLETE",title:"Persistence & Research Foundations",description:"Durable memory, journal/state persistence and research-oriented data plumbing were established."},
  {phase:7,status:"COMPLETE",title:"Trader Analytics",description:"Journal analytics added win rate, expectancy, profit factor, average win/loss, net R, drawdown, streaks and multi-dimensional breakdowns."},
  {phase:8,status:"COMPLETE",title:"Accounts & Security",description:"Optional user accounts, secure password hashing, HTTP-only sessions, account-backed memory, rate limiting and hardened response security were added."},
  {phase:9,status:"COMPLETE",title:"Deterministic Decision Engine",description:"A single final Decision Engine combined market, multi-timeframe, derivatives/order-flow, data-quality, validation and prop-firm safety context."},
  {phase:10,status:"COMPLETE",title:"Decision Center Integration",description:"The final decision layer became the authoritative dashboard state with short caching and last-known-good fail-safe behavior."},
  {phase:11,status:"COMPLETE",title:"Live Validation Gates",description:"Current freshness, risk state, fail-safe state and historical evidence checks were placed before any live-reliance indication."},
  {phase:12,status:"COMPLETE",title:"Walk-Forward Validation",description:"Rolling historical replay of deterministic decision logic was added without future-candle lookahead and with conservative same-bar conflict handling."},
  {phase:13,status:"COMPLETE",title:"Adaptive Safety",description:"Observed out-of-sample performance can tighten confluence requirements; insufficient evidence keeps decisions PAPER_ONLY."},
  {phase:14,status:"COMPLETE",title:"Signal Intelligence",description:"Setup-specific knowledge profiles, conflict resolution, regime-aware calibration and bounded historical evidence were added for SFP, NPOC, D-Line and related setups."},
  {phase:15,status:"COMPLETE",title:"Operational Intelligence",description:"The system was extended with stronger operational/learning integrations and persistent runtime diagnostics around the decision stack."},
  {phase:16,status:"COMPLETE",title:"Watchdog & Self-Healing",description:"Continuous health checks, self-tests, load-aware behavior, incident recording and guarded remediation were introduced."},
  {phase:17,status:"COMPLETE",title:"Autotrader Safety Router",description:"Execution planning and interval/strategy routing were separated from signal logic while keeping execution behind explicit safety controls."},
  {phase:18,status:"COMPLETE",title:"Market State & Execution Routing",description:"Cross-venue market-state snapshots and a planning-only smart execution router were added, with no automatic live execution enablement."},
  {phase:19,status:"COMPLETE",title:"State Synchronization & Stability",description:"Authoritative decision/state synchronization, live-price consistency and stabilized directional presentation were strengthened across Decision Center surfaces."},
  {phase:20,status:"COMPLETE",title:"Scenario Matrix & Decision Forensics",description:"LONG, SHORT and WAIT scenarios are evaluated from one canonical snapshot with evidence, next confirmations, invalidation logic and snapshot integrity."},

  {phase:21,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Canonical State Contract",description:"Create one versioned server-side contract for price, structure, derivatives, liquidity, CVD, OI, risk, validation and decision state so every surface consumes the same normalized object."},
  {phase:22,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Authoritative State Bus",description:"Introduce a single state publication pipeline with monotonic sequence numbers, timestamps, source lineage and stale-snapshot protection across charts, Decision Center and workers."},
  {phase:23,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Directional Hysteresis Engine",description:"Make LONG/SHORT/WAIT transitions deterministic with minimum hold, confirmation count, invalidation triggers and anti-flip protection enforced server-side."},
  {phase:24,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Data Quality & Provenance Layer",description:"Score every input for freshness, completeness, venue agreement, timestamp integrity and source provenance; block downstream decisions when required evidence is unreliable."},
  {phase:25,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Cross-Exchange Flow Normalization",description:"Normalize order books, trades, funding, open interest, taker flow and CVD across venues with unit-aware transformations and missing-data rules."},
  {phase:26,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Market Regime Engine 2.0",description:"Upgrade regime detection to combine trend, volatility, liquidity, derivatives crowding and structural context with explicit transition confidence and regime history."},
  {phase:27,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Liquidity & Structure Intelligence",description:"Unify liquidity pools, sweeps, SFP, D-Line, FVG, breaker, NPOC, golden-pocket and market-structure evidence into one explainable structural graph."},
  {phase:28,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Confluence Scoring 2.0",description:"Replace loosely combined signals with bounded evidence weights, conflict penalties, regime-aware thresholds and transparent reason codes."},
  {phase:29,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Signal Calibration",description:"Calibrate historical signal probabilities/confidence against resolved outcomes while preventing future leakage and separating training, calibration and evaluation windows."},
  {phase:30,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Risk Engine 2.0",description:"Centralize risk sizing, liquidation distance, max loss, correlated exposure, daily drawdown and portfolio headroom so every decision uses the same risk contract."},
  {phase:31,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Backtest Engine 2.0",description:"Build reproducible event-driven backtesting with realistic order sequencing, fees, spread, stop/target precedence and full audit trails."},
  {phase:32,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Walk-Forward Evaluation 2.0",description:"Automate rolling train/calibrate/test windows with parameter freeze rules and out-of-sample reports by asset, regime, setup and timeframe."},
  {phase:33,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Monte Carlo & Robustness Lab",description:"Stress strategy outcomes with trade-order reshuffles, slippage shocks, gap assumptions and parameter perturbations to expose fragile edges."},
  {phase:34,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Paper Execution Simulator",description:"Create a realistic paper broker with fills, partial fills, rejected orders, order lifecycle, position state and simulated exchange responses."},
  {phase:35,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Latency & Slippage Model",description:"Measure and model signal-to-order latency, spread, market impact and adverse movement so paper results are not unrealistically optimistic."},
  {phase:36,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Signal Journal & Forensics 2.0",description:"Persist every decision snapshot, evidence set, gate result, price path and outcome so any signal can be reconstructed exactly after the fact."},
  {phase:37,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Adaptive Learning Guardrails",description:"Constrain online learning with versioned models, minimum sample sizes, rollback checkpoints, holdout protection and automatic disable-on-drift behavior."},
  {phase:38,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Drift Detection",description:"Detect changes in market behavior, feature distributions, setup frequency, hit rate and execution quality before allowing stale assumptions to propagate."},
  {phase:39,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Confidence Calibration & Scoring Audit",description:"Audit confidence against realized frequencies and expose calibration error, coverage and uncertainty instead of treating scores as certainty."},
  {phase:40,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Anomaly & Market Shock Detection",description:"Detect exchange divergences, abnormal volatility, liquidity vacuum, feed freezes, sudden OI/CVD dislocations and other conditions that should force WAIT."},
  {phase:41,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Fail-Safe & Kill-Switch Framework",description:"Add layered trading locks for bad data, model drift, loss limits, infrastructure faults and operator emergency controls with explicit recovery rules."},
  {phase:42,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Observability & SLOs",description:"Add structured telemetry for data latency, decision latency, signal stability, error rates, worker health, database health and service-level objectives."},
  {phase:43,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Admin Phase History",description:"Add a permanent owner-only evolution ledger showing Phase 1 through the current phase, what changed, validation status, commit/deploy reference and known limitations."},
  {phase:44,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Decision Explainability 2.0",description:"Make every final decision explainable from the canonical snapshot with evidence, conflicts, missing confirmations, invalidation and gate outcomes."},
  {phase:45,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Security & Secrets Review",description:"Perform a full application-security pass covering authentication, MFA, authorization boundaries, CSRF, headers, secret handling, dependency risk and admin-surface isolation."},
  {phase:46,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Deployment Safety & Canary",description:"Introduce staged deployment, health-gated rollout, rollback checkpoints and production verification so a bad release does not silently alter live decision behavior."},
  {phase:47,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Backup & Disaster Recovery",description:"Strengthen database backup verification, configuration recovery, migration safety, restore drills and lossless audit preservation."},
  {phase:48,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Performance & Scale",description:"Profile hot paths, reduce redundant market calls, optimize caches and database access, bound worker concurrency and test sustained multi-symbol load."},
  {phase:49,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Live-Readiness Gate",description:"Combine data integrity, validation, robustness, paper execution, risk, security, observability and operational evidence into one hard readiness gate."},
  {phase:50,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Controlled Live-Readiness / Shadow-to-Live",description:"Run a final shadow-mode period, verify zero critical blockers, preserve rollback controls and only then expose a separately gated live-execution capability if the evidence supports it; no profitability guarantee is implied."},
  {phase:51,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Trader Signal Contract",description:"Phase 51 trader-grade signal intelligence layer."},
  {phase:52,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Signal Qualification Gate",description:"Phase 52 trader-grade signal intelligence layer."},
  {phase:53,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Setup Ensemble 2.0",description:"Phase 53 trader-grade signal intelligence layer."},
  {phase:54,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Multi-Timeframe Alignment",description:"Phase 54 trader-grade signal intelligence layer."},
  {phase:55,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Liquidity Reaction Engine",description:"Phase 55 trader-grade signal intelligence layer."},
  {phase:56,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Structure Shift Engine",description:"Phase 56 trader-grade signal intelligence layer."},
  {phase:57,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Imbalance & FVG Context",description:"Phase 57 trader-grade signal intelligence layer."},
  {phase:58,status:"IMPLEMENTED_PENDING_VALIDATION",title:"CVD/OI Divergence Engine",description:"Phase 58 trader-grade signal intelligence layer."},
  {phase:59,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Derivatives Crowding Engine",description:"Phase 59 trader-grade signal intelligence layer."},
  {phase:60,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Cross-Venue Consensus 2.0",description:"Phase 60 trader-grade signal intelligence layer."},
  {phase:61,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Session & Volatility Context",description:"Phase 61 trader-grade signal intelligence layer."},
  {phase:62,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Trigger Quality Engine",description:"Phase 62 trader-grade signal intelligence layer."},
  {phase:63,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Invalidation Engine 2.0",description:"Phase 63 trader-grade signal intelligence layer."},
  {phase:64,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Adaptive Levels Engine",description:"Phase 64 trader-grade signal intelligence layer."},
  {phase:65,status:"IMPLEMENTED_PENDING_VALIDATION",title:"R:R & Expectancy Gate",description:"Phase 65 trader-grade signal intelligence layer."},
  {phase:66,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Exchange Risk Translator",description:"Phase 66 trader-grade signal intelligence layer."},
  {phase:67,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Leverage & Liquidation Safety",description:"Phase 67 trader-grade signal intelligence layer."},
  {phase:68,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Signal TTL & Aging",description:"Phase 68 trader-grade signal intelligence layer."},
  {phase:69,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Signal Lifecycle State Machine",description:"Phase 69 trader-grade signal intelligence layer."},
  {phase:70,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Anti-Chop & Cooldown",description:"Phase 70 trader-grade signal intelligence layer."},
  {phase:71,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Probability Calibration 2.0",description:"Phase 71 trader-grade signal intelligence layer."},
  {phase:72,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Ensemble Confidence Engine",description:"Phase 72 trader-grade signal intelligence layer."},
  {phase:73,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Uncertainty & Coverage Engine",description:"Phase 73 trader-grade signal intelligence layer."},
  {phase:74,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Cost-Aware Expectancy Engine",description:"Phase 74 trader-grade signal intelligence layer."},
  {phase:75,status:"IMPLEMENTED_PENDING_VALIDATION",title:"MAE Analytics",description:"Phase 75 trader-grade signal intelligence layer."},
  {phase:76,status:"IMPLEMENTED_PENDING_VALIDATION",title:"MFE Analytics",description:"Phase 76 trader-grade signal intelligence layer."},
  {phase:77,status:"IMPLEMENTED_PENDING_VALIDATION",title:"False-Positive Taxonomy",description:"Phase 77 trader-grade signal intelligence layer."},
  {phase:78,status:"IMPLEMENTED_PENDING_VALIDATION",title:"False-Negative Taxonomy",description:"Phase 78 trader-grade signal intelligence layer."},
  {phase:79,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Missed-Signal Analytics",description:"Phase 79 trader-grade signal intelligence layer."},
  {phase:80,status:"IMPLEMENTED_PENDING_VALIDATION",title:"No-Trade Quality Engine",description:"Phase 80 trader-grade signal intelligence layer."},
  {phase:81,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Shadow Learning Engine",description:"Phase 81 trader-grade signal intelligence layer."},
  {phase:82,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Champion / Challenger Models",description:"Phase 82 trader-grade signal intelligence layer."},
  {phase:83,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Drift Recovery Engine",description:"Phase 83 trader-grade signal intelligence layer."},
  {phase:84,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Parameter Guardrails 2.0",description:"Phase 84 trader-grade signal intelligence layer."},
  {phase:85,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Live Signal Monitoring",description:"Phase 85 trader-grade signal intelligence layer."},
  {phase:86,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Symbol Correlation Engine",description:"Phase 86 trader-grade signal intelligence layer."},
  {phase:87,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Portfolio Risk Aggregator",description:"Phase 87 trader-grade signal intelligence layer."},
  {phase:88,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Event & News Risk Layer",description:"Phase 88 trader-grade signal intelligence layer."},
  {phase:89,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Exchange Health Layer",description:"Phase 89 trader-grade signal intelligence layer."},
  {phase:90,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Trader Execution Checklist",description:"Phase 90 trader-grade signal intelligence layer."},
  {phase:91,status:"IMPLEMENTED_PENDING_VALIDATION",title:"User Context Profile",description:"Phase 91 trader-grade signal intelligence layer."},
  {phase:92,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Beginner Mode",description:"Phase 92 trader-grade signal intelligence layer."},
  {phase:93,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Decision Timeline",description:"Phase 93 trader-grade signal intelligence layer."},
  {phase:94,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Signal Notification Tiers",description:"Phase 94 trader-grade signal intelligence layer."},
  {phase:95,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Public Signal History",description:"Phase 95 trader-grade signal intelligence layer."},
  {phase:96,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Live Signal Scorecard",description:"Phase 96 trader-grade signal intelligence layer."},
  {phase:97,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Outcome Feedback Loop",description:"Phase 97 trader-grade signal intelligence layer."},
  {phase:98,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Public Audit & Transparency",description:"Phase 98 trader-grade signal intelligence layer."},
  {phase:99,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Free Public Readiness Gate",description:"Phase 99 trader-grade signal intelligence layer."},
  {phase:100,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Public Signal Gate 1.0",description:"Phase 100 trader-grade signal intelligence layer."},
  {phase:101,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Market State Reconstruction 2.0",description:"Reconstruct synchronized market state from price, candles, derivatives, liquidity and live flow."},
  {phase:102,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Microstructure Engine 2.0",description:"Measure aggressive flow, order-book pressure and execution pressure."},
  {phase:103,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Liquidity Migration Engine",description:"Track movement of nearby liquidity and price interaction with it."},
  {phase:104,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Liquidity Sweep Classification",description:"Classify sweeps as reaction, continuation, failed break or unresolved noise."},
  {phase:105,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Order-Flow Regime Detection",description:"Classify accumulation, distribution, absorption, expansion and exhaustion."},
  {phase:106,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Volume-Price Relationship Engine",description:"Detect volume and price agreement, divergence and abnormal participation."},
  {phase:107,status:"IMPLEMENTED_PENDING_VALIDATION",title:"OI Lifecycle Engine",description:"Classify open-interest changes with price and aggressive flow."},
  {phase:108,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Funding/Basis Intelligence",description:"Turn funding and basis into contextual crowding evidence."},
  {phase:109,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Liquidation Pressure Map",description:"Map observed liquidation pressure and sensitive regions."},
  {phase:110,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Market Pressure Composite",description:"Combine pressure components while preserving provenance and uncertainty."},
  {phase:111,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Structure Engine 3.0",description:"Reconstruct higher-high/lower-low structure, BOS, CHoCH and structural state."},
  {phase:112,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Swing Quality Engine",description:"Separate meaningful swings from low-information pivots."},
  {phase:113,status:"IMPLEMENTED_PENDING_VALIDATION",title:"SFP Intelligence 2.0",description:"Contextualize swing-failure patterns with structure and liquidity."},
  {phase:114,status:"IMPLEMENTED_PENDING_VALIDATION",title:"D-Line Intelligence 2.0",description:"Contextualize D-Line setups with higher-timeframe structure and flow."},
  {phase:115,status:"IMPLEMENTED_PENDING_VALIDATION",title:"FVG Quality Engine",description:"Rank imbalance zones by freshness, reaction and structure."},
  {phase:116,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Breaker / Mitigation Engine",description:"Assess breaker and mitigation zones using structural evidence."},
  {phase:117,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Golden Pocket Context Engine",description:"Use Fibonacci context only with independent structural confirmation."},
  {phase:118,status:"IMPLEMENTED_PENDING_VALIDATION",title:"NPOC / Volume Profile Intelligence",description:"Model acceptance and rejection around volume-profile references."},
  {phase:119,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Multi-Pattern Relationship Graph",description:"Model relationships among SFP, D-Line, FVG, breaker, NPOC and liquidity."},
  {phase:120,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Price Action Narrative Engine",description:"Create a machine-readable current price-action narrative."},
  {phase:121,status:"IMPLEMENTED_PENDING_VALIDATION",title:"12-Timeframe State Engine",description:"Build synchronized state across available timeframes."},
  {phase:122,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Timeframe Conflict Resolver",description:"Measure and classify higher/lower timeframe disagreement."},
  {phase:123,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Regime Transition Detector 3.0",description:"Detect transitions between trend, range, compression and expansion."},
  {phase:124,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Trend Strength Engine",description:"Separate persistent direction from weak directional noise."},
  {phase:125,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Range Intelligence Engine",description:"Identify range boundaries, acceptance and mean-reversion context."},
  {phase:126,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Expansion/Compression Detector",description:"Detect compression and transition into expansion."},
  {phase:127,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Breakout Quality Engine",description:"Distinguish confirmed expansion from low-quality breakout attempts."},
  {phase:128,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Reversal Probability Context",description:"Describe reversal evidence without unsupported probabilities."},
  {phase:129,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Session Transition Intelligence",description:"Track behavior around major session transitions."},
  {phase:130,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Regime-Specific Signal Policies",description:"Apply regime-specific evidence requirements."},
  {phase:131,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Signal Ensemble 2.0",description:"Combine independent evidence streams while limiting double-counting."},
  {phase:132,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Evidence Independence Engine",description:"Estimate whether confirmations represent independent evidence."},
  {phase:133,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Signal Conflict Matrix",description:"Surface contradictory evidence explicitly."},
  {phase:134,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Signal Strength Decomposition",description:"Show which evidence components contribute to direction."},
  {phase:135,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Signal Sequence Intelligence",description:"Track whether confirmation order changes signal quality."},
  {phase:136,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Setup Maturity Engine",description:"Classify setups as developing, confirmed, extended or exhausted."},
  {phase:137,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Pre-Trigger Intelligence",description:"Detect setup formation without calling it actionable."},
  {phase:138,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Trigger Confirmation 2.0",description:"Strengthen trigger confirmation using close, retest and flow conditions."},
  {phase:139,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Signal Quality Ranking Engine",description:"Produce internal evidence-quality classification without fake performance scores."},
  {phase:140,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Decision Center 3.0",description:"Create one authoritative explanation of LONG, SHORT or WAIT."},
  {phase:141,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Probability Engine 3.0",description:"Use only supplied validated probabilities."},
  {phase:142,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Regime-Conditional Probability",description:"Condition empirical probability on comparable regimes."},
  {phase:143,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Setup-Specific Probability Models",description:"Keep probability evidence segmented by setup family."},
  {phase:144,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Time-Horizon Probability Curves",description:"Represent validated outcome rates across multiple horizons."},
  {phase:145,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Calibration Engine 3.0",description:"Measure whether reported probabilities match observed frequencies."},
  {phase:146,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Reliability Curves & Calibration Error",description:"Calculate reliability and calibration error from outcome pairs."},
  {phase:147,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Uncertainty Decomposition",description:"Separate data, model and market uncertainty."},
  {phase:148,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Prediction Interval Engine",description:"Prefer ranges when point estimates imply false precision."},
  {phase:149,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Confidence Collapse Detector",description:"Detect unstable evidence that should reduce confidence."},
  {phase:150,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Prediction Evidence Ledger",description:"Create auditable evidence snapshots for predictions."},
  {phase:151,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Market Replay Engine 2.0",description:"Replay historical states using only information available at each timestamp."},
  {phase:152,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Scenario Library",description:"Build reusable historical scenario descriptors."},
  {phase:153,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Similarity Retrieval Engine",description:"Find structurally similar historical states."},
  {phase:154,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Counterfactual Analysis",description:"Compare alternative decisions without rewriting recorded history."},
  {phase:155,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Missed-Trade Analysis 2.0",description:"Separate missed opportunities from correct WAIT decisions."},
  {phase:156,status:"IMPLEMENTED_PENDING_VALIDATION",title:"False-Positive Root Cause Engine",description:"Classify why bad signals passed."},
  {phase:157,status:"IMPLEMENTED_PENDING_VALIDATION",title:"False-Negative Root Cause Engine",description:"Classify why useful setups were rejected."},
  {phase:158,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Feature Contribution Forensics",description:"Attribute outcomes to evidence groups without causal overclaiming."},
  {phase:159,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Learning Safety Sandbox",description:"Test learned changes in isolation."},
  {phase:160,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Evidence Promotion Engine",description:"Promote changes only after objective out-of-sample checks."},
  {phase:161,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Concept Drift Engine 2.0",description:"Detect changes in feature/outcome relationships."},
  {phase:162,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Strategy Decay Detector",description:"Detect meaningful degradation in setup behavior."},
  {phase:163,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Regime Drift Detector",description:"Detect when historical comparison populations become mismatched."},
  {phase:164,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Adaptive Threshold Engine",description:"Adjust thresholds only inside validated hard bounds."},
  {phase:165,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Champion/Challenger 2.0",description:"Compare challengers against the active baseline in shadow mode."},
  {phase:166,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Automatic Challenger Rejection",description:"Reject weak challengers without changing active logic."},
  {phase:167,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Rollback Intelligence",description:"Define deterministic rollback eligibility on degradation."},
  {phase:168,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Learning Contamination Guard",description:"Detect future leakage and timestamp contamination."},
  {phase:169,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Data Snooping Defense",description:"Track experiment reuse and overfit risk."},
  {phase:170,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Adaptive-System Audit Trail",description:"Record adaptive changes and reasons."},
  {phase:171,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Dynamic Invalidation Engine 2.0",description:"Keep invalidation structural and adaptive without weakening hard risk limits."},
  {phase:172,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Dynamic TP Architecture",description:"Build targets from structure and empirical excursion."},
  {phase:173,status:"IMPLEMENTED_PENDING_VALIDATION",title:"MAE/MFE Distribution Engine 2.0",description:"Use empirical excursion distributions for planning."},
  {phase:174,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Slippage Scenario Engine 2.0",description:"Stress planned execution under slippage scenarios."},
  {phase:175,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Fee & Funding Impact Engine 2.0",description:"Include trading costs in expectancy context."},
  {phase:176,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Position-Sizing Evidence Engine",description:"Tie sizing context to volatility, structure and hard limits."},
  {phase:177,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Correlation Stress Engine",description:"Detect hidden concentration across positions."},
  {phase:178,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Liquidation Safety Engine",description:"Detect dangerous leverage and liquidation distances."},
  {phase:179,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Exchange Execution Context",description:"Track exchange-specific execution assumptions and constraints."},
  {phase:180,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Manual Execution Safety Router 2.0",description:"Keep execution decision-support-only and route unsafe conditions away from action."},
  {phase:181,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Decision Center 4.0",description:"Create a structured explanation-first trader cockpit payload."},
  {phase:182,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Signal Timeline",description:"Represent signal development and state transitions."},
  {phase:183,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Live Evidence Map",description:"Present synchronized liquidity, flow, structure and trigger relationships."},
  {phase:184,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Why No Trade 2.0",description:"Create precise blocker hierarchy and next-confirmation guidance."},
  {phase:185,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Trade Preparation Mode",description:"Show what must happen before a developing setup becomes actionable."},
  {phase:186,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Signal Lifecycle UI",description:"Expose setup lifecycle from developing to expired."},
  {phase:187,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Beginner/Advanced Adaptive UI",description:"Change explanation depth without changing underlying decisions."},
  {phase:188,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Mobile Trading Cockpit",description:"Return compact decision-support presentation metadata."},
  {phase:189,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Alert Intelligence 2.0",description:"Emit material-state-change notifications rather than repeats."},
  {phase:190,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Personal Trading Journal Integration",description:"Package structured decision records for journal persistence."},
  {phase:191,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Admin Intelligence Console 2.0",description:"Expose an admin intelligence summary."},
  {phase:192,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Signal Forensics Dashboard",description:"Provide signal evidence and outcome-forensics metadata."},
  {phase:193,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Model Health Dashboard",description:"Summarize calibration, drift, errors, latency and quality."},
  {phase:194,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Data Source Reliability Matrix",description:"Summarize source freshness, availability and disagreement."},
  {phase:195,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Incident Detection & Response Engine",description:"Identify feed, staleness and consistency incidents."},
  {phase:196,status:"IMPLEMENTED_PENDING_VALIDATION",title:"System Self-Test 2.0",description:"Run deterministic integrity checks across the advanced pipeline."},
  {phase:197,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Public Transparency Center",description:"Prepare public-safe outcome and methodology metadata."},
  {phase:198,status:"IMPLEMENTED_PENDING_VALIDATION",title:"User Safety Center",description:"Expose risk, leverage, staleness and execution warnings."},
  {phase:199,status:"IMPLEMENTED_PENDING_VALIDATION",title:"Public Signal Trust Layer",description:"Require evidence-backed readiness for public signal presentation."},
  {phase:200,status:"IMPLEMENTED_PENDING_VALIDATION",title:"MarketPulse Intelligence OS 2.0",description:"Finalize the integrated controlled promotion contract."}
];

function getPhaseHistory(){
  return phases.map(p=>({...p}));
}
function getCurrentPhase(){
  const complete=phases.filter(p=>p.status==="COMPLETE");
  return complete.length?Math.max(...complete.map(p=>p.phase)):0;
}
module.exports={phases,getPhaseHistory,getCurrentPhase};
